#!/usr/bin/env node
/**
 * @module ai/scripts/lifecycle/hooks/projectSeatHooks
 * @summary Materializes the Agent-OS-owned seat hooks into a target checkout as generated-not-tracked artifacts.
 *
 * Seat hooks are Agent OS substrate that must *execute* inside an arbitrary target repository. The
 * sources live here; the target gets generated copies whose Brain-substrate specifiers are rewritten
 * to absolute paths beneath the runtime root. That rewrite is the whole reason these are generated
 * rather than copied verbatim: a relative specifier resolved from the target would climb out of a
 * tree that does not contain this repository.
 *
 * **Why copies and not symlinks — measured, not assumed.** Symlinking is the transport the sibling
 * skills materializer uses, and for skills it is correct: those are data files, read and never run.
 * Hooks are executables, and every one of them gates `main()` on
 * `import.meta.url === pathToFileURL(process.argv[1]).href`. Through a symlink `argv[1]` keeps the
 * link path while `import.meta.url` resolves to the realpath, so the guard is false: the module
 * loads, `main()` never runs, the process exits 0, and nothing anywhere reports a problem. A
 * silently dead hook is the exact failure this projection exists to end, so the transport that
 * produces one is unavailable regardless of how convenient it is.
 *
 * Two roots, never conflated (ADR 0040 §2.5): `agentosRuntimeRoot` is where the sources live and
 * what rewritten specifiers point at; `targetRepoRoot` is the destination only. Neither defaults to
 * `process.cwd()` — an absent binding fails loud rather than silently projecting into whatever
 * directory the process happened to start in.
 */
import {execFileSync}                      from 'node:child_process';
import fs                                  from 'node:fs';
import path                                from 'node:path';
import {fileURLToPath, pathToFileURL}      from 'node:url';

const
    dirname = path.dirname(fileURLToPath(import.meta.url)),
    /**
     * Source directory → target directory, per harness. The target segments are dot-prefixed by the
     * harnesses themselves; the source segments are not, because a dotted source directory is
     * hostile to tooling and to diffing a projection against its origin.
     */
    HARNESS_TARGETS = Object.freeze({
        'claude'   : '.claude/hooks',
        'codex'    : '.codex/hooks',
        'kimi-code': '.kimi-code/hooks'
    }),
    /** Marks a generated artifact so a reader never mistakes a projection for an authored file. */
    GENERATED_BANNER = '// GENERATED by ai/scripts/lifecycle/hooks/projectSeatHooks.mjs — do not edit.\n' +
                       '// Source of truth: <agentosRuntimeRoot>/ai/scripts/lifecycle/hooks/\n';

/**
 * @summary Is a path tracked by the target's git? A tracked path is authored content, not projection.
 * @param {String} root Target repository root.
 * @param {String} relPath Repository-relative path.
 * @returns {Boolean}
 */
export function tracked(root, relPath) {
    try {
        execFileSync('git', ['ls-files', '--error-unmatch', '--', relPath], {cwd: root, stdio: 'ignore'});
        return true
    } catch {
        return false
    }
}

/**
 * @summary Enumerates every projectable hook as `{harness, source, target}` triples.
 * @param {String} runtimeRoot Absolute AgentOS runtime root.
 * @returns {Object[]}
 */
export function enumerateHooks(runtimeRoot) {
    const hooks = [];

    Object.entries(HARNESS_TARGETS).forEach(([harness, targetDir]) => {
        const sourceDir = path.join(runtimeRoot, 'ai/scripts/lifecycle/hooks', harness);

        if (!fs.existsSync(sourceDir)) return;

        fs.readdirSync(sourceDir)
            .filter(name => name.endsWith('.mjs'))
            .sort()
            .forEach(name => hooks.push({
                harness,
                source: path.join(sourceDir, name),
                target: path.posix.join(targetDir, name)
            }))
    });

    return hooks
}

/**
 * @summary Rewrites Brain-substrate specifiers to absolute paths beneath the runtime root.
 *
 * Only `../`-relative specifiers are touched, and only those that resolve inside the runtime root.
 * Package specifiers (`neo.mjs/src/**`) are deliberately left alone: they resolve through the
 * target's own `node_modules` against the published Engine, which is the §2.3 dependency direction.
 * A specifier that resolves OUTSIDE the runtime root is returned unchanged and reported, because
 * silently rewriting it would invent a dependency the source never declared.
 * @param {String} contents Source text.
 * @param {String} sourceFile Absolute path of the source module.
 * @param {String} runtimeRoot Absolute AgentOS runtime root.
 * @returns {{contents: String, rewritten: Number, escaped: String[]}}
 */
export function rewriteSpecifiers(contents, sourceFile, runtimeRoot) {
    const
        sourceDir = path.dirname(sourceFile),
        escaped   = [];

    let rewritten = 0;

    const next = contents.replace(/(['"])(\.\.?\/[^'"]+)\1/g, (match, quote, specifier) => {
        const resolved = path.resolve(sourceDir, specifier);

        if (!resolved.startsWith(runtimeRoot + path.sep)) {
            escaped.push(specifier);
            return match
        }

        rewritten++;
        return `${quote}${resolved}${quote}`
    });

    return {contents: next, escaped, rewritten}
}

/**
 * @summary Compares what is projected against what should be, without writing anything.
 *
 * Reports four independent conditions, because they need different answers: `missing` means the
 * seat will silently run nothing; `stale` means it runs an older revision than the source;
 * `trackedConflicts` means an authored file occupies a projection path and must never be
 * overwritten; `escapedSpecifiers` means a source reaches outside the runtime root and the
 * projection cannot bind it.
 * @param {Object} options
 * @param {String} options.agentosRuntimeRoot
 * @param {String} options.targetRepoRoot
 * @returns {{escapedSpecifiers: Object[], missing: String[], ok: Boolean, stale: String[], trackedConflicts: String[]}}
 */
export function checkProjection({agentosRuntimeRoot, targetRepoRoot}) {
    const
        escapedSpecifiers = [],
        missing           = [],
        stale             = [],
        trackedConflicts  = [];

    enumerateHooks(agentosRuntimeRoot).forEach(({source, target}) => {
        const
            absTarget = path.join(targetRepoRoot, target),
            expected  = renderProjection(source, agentosRuntimeRoot);

        if (expected.escaped.length) escapedSpecifiers.push({escaped: expected.escaped, target});

        if (tracked(targetRepoRoot, target)) {
            trackedConflicts.push(target);
            return
        }

        if (!fs.existsSync(absTarget)) {
            missing.push(target);
            return
        }

        if (fs.readFileSync(absTarget, 'utf8') !== expected.contents) stale.push(target)
    });

    return {
        escapedSpecifiers,
        missing,
        ok: !missing.length && !stale.length && !trackedConflicts.length && !escapedSpecifiers.length,
        stale,
        trackedConflicts
    }
}

/**
 * @summary Produces the exact bytes a projected hook must contain.
 * @param {String} source Absolute source path.
 * @param {String} runtimeRoot Absolute AgentOS runtime root.
 * @returns {{contents: String, escaped: String[], rewritten: Number}}
 */
export function renderProjection(source, runtimeRoot) {
    const
        raw     = fs.readFileSync(source, 'utf8'),
        result  = rewriteSpecifiers(raw, source, runtimeRoot),
        shebang = raw.startsWith('#!') ? '' : GENERATED_BANNER;

    // A shebang must stay on line 1, so the banner follows it rather than displacing it.
    return {
        ...result,
        contents: shebang
            ? shebang + result.contents
            : result.contents.replace(/^(#![^\n]*\n)/, `$1${GENERATED_BANNER}`)
    }
}

export {HARNESS_TARGETS};
